Feature/inform client about offers IO-50
IO-2023-project/software-engineering-project pull request #15
Opened 2023-06-15 19:20 UTC by my-alaska

2023-06-16 19:11 UTC, tunczyk101 requested changes
Jest ok
Jedynie zmiany kosmetyczne

2023-06-16 19:11 UTC, tunczyk101 commented on ioproject/mail/send_email.py
> +    msg["Subject"] = f"Mechanik - Przykładowe oferty"
Korekta *humanistyczna*
Tytuł trochę nie pasuje
Dlaczego *przykładowe*?
Np. *(za)proponowane oferty* / *zaproponowano oferty* - większa personalizacja przy użyciu słowa "(za)proponowane"

2023-06-16 19:14 UTC, tunczyk101 commented on ioproject/mail/send_email.py
> +            f"Twój Pan Mechanik")
Tu można wstawić `\n` przed podpisem Pana Mechanika

2023-06-17 21:34 UTC, my-alaska commented on ioproject/orders/views.py
> +import mail.send_email as mail
done

2023-06-17 21:35 UTC, my-alaska commented on ioproject/mail/send_email.py
> +
done

2023-06-17 21:35 UTC, my-alaska commented on ioproject/mail/send_email.py
> +
done

2023-06-17 21:36 UTC, my-alaska commented on ioproject/mail/send_email.py
> +    msg["Subject"] = f"Mechanik - Przykładowe oferty"
zmieniłem na proponowane oferty

2023-06-17 21:40 UTC, my-alaska commented on ioproject/mail/send_email.py
> +            f"Twój Pan Mechanik")
done

2023-06-18 00:12 UTC, tunczyk101 approved these changes

2023-06-18 10:51 UTC, merged